# Generated by Django 3.2.12 on 2024-02-06 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='varient_quantity',
        ),
    ]
