# Generated by Django 3.2.12 on 2024-03-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('amount', 'Amount')], max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='stock',
            field=models.SmallIntegerField(),
        ),
    ]
