# Generated by Django 4.2.6 on 2023-10-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0002_alter_categories_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='Gstin',
            new_name='gstin',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='Vat',
            new_name='vat',
        ),
        migrations.RemoveField(
            model_name='productmedia',
            name='media_type',
        ),
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
