# Generated by Django 3.2.12 on 2024-02-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(max_length=36, null=True, verbose_name='Payment ID'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='provider_order_id',
            field=models.CharField(max_length=40, null=True, verbose_name='Order ID'),
        ),
        migrations.AddField(
            model_name='order',
            name='signature_id',
            field=models.CharField(max_length=128, null=True, verbose_name='Signature ID'),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
