# Generated by Django 4.2.6 on 2023-10-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0005_remove_products_brand_alter_wishlist_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
