# Generated by Django 3.2.12 on 2024-03-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0006_alter_order_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_delivery', models.TextField(max_length=1000)),
                ('safe_payment', models.TextField(max_length=1000)),
                ('secure_payment', models.TextField(max_length=1000)),
                ('Back_Guarantee', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Flutterwave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=500)),
                ('flutterwave_key', models.CharField(max_length=500)),
                ('flutterwave_secret_key', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='InstaMOJO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=500)),
                ('instamojo_environment', models.CharField(max_length=500)),
                ('instamojo_key', models.CharField(max_length=500)),
                ('instamojo_token', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Msg91',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg91_auth_key', models.CharField(max_length=500)),
                ('msg91_sender_id', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=500)),
                ('page_image', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('Page_content', models.TextField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Paypal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=500)),
                ('paypal_client_key', models.CharField(max_length=500)),
                ('paypal_client_secret', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PayStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=500)),
                ('paystack_sk', models.CharField(max_length=500)),
                ('paystack_pk', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PayTM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=500)),
                ('paytm_environment', models.CharField(max_length=500)),
                ('paytm_merchant_key', models.CharField(max_length=500)),
                ('paytm_merchant_MID', models.CharField(max_length=500)),
                ('paytm_merchant_website', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Stripe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=500)),
                ('stripe_key', models.CharField(max_length=500)),
                ('stripe_secret', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Twilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twilio_SID', models.CharField(max_length=500)),
                ('twilio_auth_token', models.CharField(max_length=500)),
                ('twilio_from_number', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='returns_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='shipping_amount',
            field=models.FloatField(default=40),
        ),
    ]
