# Generated by Django 3.2.12 on 2024-03-28 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0007_auto_20240325_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreviews',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to='ecommerce_app.products'),
        ),
    ]
