# Generated by Django 3.2.12 on 2024-02-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0008_auto_20240214_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='final_price',
            field=models.FloatField(default=0),
        ),
    ]
