# Generated by Django 3.2.12 on 2024-04-05 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0008_alter_productreviews_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_title', models.CharField(max_length=50)),
                ('payment_response', models.TextField(max_length=3000)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.order')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='RazorpayPayment',
        ),
    ]
