# Generated by Django 3.2.12 on 2024-02-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0009_products_final_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discount',
            field=models.FloatField(default=0),
        ),
    ]
