# Generated by Django 3.2.12 on 2024-04-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0009_auto_20240405_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliveryman_image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('vehicle', models.CharField(max_length=245)),
                ('identity_type', models.CharField(max_length=245)),
                ('identity_image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('identity_number', models.CharField(max_length=245)),
            ],
        ),
    ]
