# Generated by Django 3.2.12 on 2024-02-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0010_alter_products_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='you_save',
            field=models.FloatField(default=0),
        ),
    ]
