# Generated by Django 3.2.12 on 2024-03-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0011_products_you_save'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreviews',
            name='review_image',
        ),
        migrations.AddField(
            model_name='productreviews',
            name='review_image1',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='productreviews',
            name='review_image2',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='productreviews',
            name='review_image3',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='productreviews',
            name='review_image4',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='productreviews',
            name='review_image5',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
