# Generated by Django 4.2.3 on 2023-09-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0011_alter_payment_transaction_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.PositiveSmallIntegerField()),
                ('reason', models.CharField(choices=[(1, 'The price of the product has fallen due to sales/discounts.'), (2, 'Cheaper alternative available for lesser price.'), (3, 'Order delivered time is too much'), (4, 'others')], max_length=100)),
                ('others', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
