# Generated by Django 3.2.12 on 2024-03-15 07:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0012_auto_20240315_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreviews',
            name='rating',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(5)]),
        ),
    ]
