# Generated by Django 3.2.12 on 2024-04-18 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0013_auto_20240418_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryprofile',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.customuser'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=100),
        ),
    ]
