# Generated by Django 3.2.12 on 2024-04-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0014_auto_20240418_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='default_ZIP',
        ),
        migrations.RemoveField(
            model_name='store',
            name='default_city',
        ),
        migrations.RemoveField(
            model_name='store',
            name='have_shop',
        ),
        migrations.AddField(
            model_name='store',
            name='app_store',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='play_store',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='twitter',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
