# Generated by Django 3.2.12 on 2024-04-24 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0015_auto_20240422_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='store',
            name='shipping_amount',
        ),
    ]
