# Generated by Django 4.2.6 on 2023-10-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0016_alter_brand_brand_image_alter_categories_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
