# Generated by Django 3.2.12 on 2024-04-24 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0017_auto_20240424_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('order placed', 'Order placed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('canceled', 'Canceled')], default='order placed', max_length=20),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_delivered', models.BooleanField(default=False)),
                ('order', models.ForeignKey(limit_choices_to={'status': 'order placed'}, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='ecommerce_app.order')),
                ('user', models.ForeignKey(limit_choices_to={'role': 'delivery'}, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
