# Generated by Django 3.2.12 on 2024-04-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0018_auto_20240424_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='Page_content',
            field=models.TextField(max_length=10000),
        ),
    ]
