# Generated by Django 3.2.12 on 2024-05-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0019_alter_page_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_charge',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='gst',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
