# Generated by Django 3.2.12 on 2024-05-09 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0020_auto_20240509_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_charge',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='gst',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(),
        ),
    ]
