# Generated by Django 3.2.12 on 2024-05-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0021_auto_20240509_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivered_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='assigned_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
